Repository cs7290/stinky, pull requests merged in 2022-12, with the labels that each got.

#40 Add word count, schools, fly to and some formatting.
  docs/index.html
Labels: enhancement

#43 Removing a typo from the dropdown
  docs/index.html
Labels: bug

#55 In-progress repo documentation
  README.md
  docs/README.md
Labels: documentation

#62 59 add better grouping for the what does it smell like bar chart
  docs/index.html
Labels: enhancement
